#!/usr/bin/env python3
"""Fast10 Observer harness.

This script is a no-key observer layer for membot. It does not place orders and
it does not require a wallet private key. In a network-enabled monitoring run,
it consumes detector-emitted signal candidates, requests a Jupiter quote, and
writes `observer_latency_live.csv` with detector/quote/total latency breakdown.

Current scope:
- input = CSV or JSONL generated by an upstream detector/replay process
- quote = Jupiter Swap API V2 `/order` without signing or executing
- output = mandatory latency CSV + JSON summary

Not in scope yet:
- raw on-chain Fast10 detection from websocket/Geyser data
- transaction signing
- live order execution
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Iterable

import requests
from dotenv import load_dotenv
from observer_gate_eval import REQUIRED_FIELDS

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")

DEFAULT_OUTPUT = ROOT / "data" / "processed" / "observer_latency_live.csv"
DEFAULT_INPUT_MINT = "So11111111111111111111111111111111111111112"
DEFAULT_OUTPUT_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
DEFAULT_SLIPPAGE_BPS = 100
FAST10_THRESHOLD = Decimal("0.08807064065984926")
JUPITER_BASE_URL = os.getenv("JUPITER_BASE_URL", "https://api.jup.ag/swap/v2").rstrip("/")
JUPITER_API_KEY = os.getenv("JUPITER_API_KEY", "").strip()
JUPITER_TAKER = os.getenv("JUPITER_TAKER", "").strip()
TIMEOUT_SECONDS = float(os.getenv("JUPITER_TIMEOUT_SECONDS", "10"))


@dataclass
class SignalCandidate:
    signal_id: str
    token_mint: str
    signal_chain_time: datetime
    detected_local_time: datetime
    input_mint: str
    output_mint: str
    amount: int
    slippage_bps: int
    context_slot: str
    volume_accel_10_300: Decimal | None = None


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


def isoformat_z(value: datetime) -> str:
    return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def epoch_ms(value: datetime) -> int:
    return int(value.astimezone(timezone.utc).timestamp() * 1000)


def parse_datetime(value: Any, fallback: datetime | None = None) -> datetime:
    if value in (None, "", "null"):
        if fallback is not None:
            return fallback
        return now_utc()
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(float(value), tz=timezone.utc)
    raw = str(value).strip()
    if raw.isdigit():
        return datetime.fromtimestamp(float(raw), tz=timezone.utc)
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return fallback if fallback is not None else now_utc()
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def parse_decimal(value: Any) -> Decimal | None:
    if value in (None, "", "null"):
        return None
    try:
        return Decimal(str(value))
    except InvalidOperation:
        return None


def parse_int(value: Any, default: int) -> int:
    if value in (None, "", "null"):
        return default
    try:
        return int(str(value))
    except ValueError:
        return default


def parse_float(value: Any) -> float | None:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def percentile(values: list[float], q: float) -> float | None:
    if not values:
        return None
    if len(values) == 1:
        return values[0]
    ordered = sorted(values)
    idx = (len(ordered) - 1) * q
    lower = math.floor(idx)
    upper = math.ceil(idx)
    if lower == upper:
        return ordered[lower]
    return ordered[lower] + (ordered[upper] - ordered[lower]) * (idx - lower)


def iter_csv_rows(path: Path) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            yield dict(row)


def iter_jsonl_rows(path: Path) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw:
                continue
            payload = json.loads(raw)
            if isinstance(payload, dict):
                yield payload


def iter_rows(path: Path) -> Iterable[dict[str, Any]]:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        yield from iter_csv_rows(path)
        return
    if suffix in {".jsonl", ".ndjson"}:
        yield from iter_jsonl_rows(path)
        return
    raise RuntimeError(f"Unsupported input format: {path.name}")


def normalize_signal(row: dict[str, Any], index: int, threshold: Decimal) -> SignalCandidate | None:
    signal_chain_time = parse_datetime(
        row.get("signal_chain_time") or row.get("signal_time") or row.get("timestamp")
    )
    detected_local_time = parse_datetime(row.get("detected_local_time"), fallback=now_utc())
    token_mint = str(
        row.get("token_mint")
        or row.get("output_mint")
        or row.get("mint")
        or row.get("token")
        or ""
    ).strip()
    input_mint = str(row.get("input_mint") or DEFAULT_INPUT_MINT).strip()
    output_mint = str(row.get("output_mint") or token_mint or DEFAULT_OUTPUT_MINT).strip()
    amount = parse_int(row.get("amount") or row.get("amount_raw") or row.get("in_amount"), 0)
    slippage_bps = parse_int(row.get("slippage_bps"), DEFAULT_SLIPPAGE_BPS)
    accel = parse_decimal(row.get("volume_accel_10_300"))
    passes_flag = str(row.get("signal_pass") or row.get("passes_fast10") or "").strip().lower()

    if accel is not None and accel < threshold:
        return None
    if passes_flag in {"0", "false", "no"}:
        return None
    if not token_mint or not output_mint:
        return None
    if amount <= 0:
        return None

    signal_id = str(row.get("signal_id") or f"signal_{index:06d}")
    context_slot = str(row.get("context_slot") or row.get("slot") or "")

    return SignalCandidate(
        signal_id=signal_id,
        token_mint=token_mint,
        signal_chain_time=signal_chain_time,
        detected_local_time=detected_local_time,
        input_mint=input_mint,
        output_mint=output_mint,
        amount=amount,
        slippage_bps=slippage_bps,
        context_slot=context_slot,
        volume_accel_10_300=accel,
    )


def jupiter_headers() -> dict[str, str]:
    if not JUPITER_API_KEY:
        raise RuntimeError("Missing JUPITER_API_KEY. Jupiter Swap API V2 docs currently require x-api-key.")
    return {"x-api-key": JUPITER_API_KEY}


def request_quote(signal: SignalCandidate) -> dict[str, Any]:
    request_started = now_utc()
    monotonic_request_start = time.perf_counter()
    response = requests.get(
        f"{JUPITER_BASE_URL}/order",
        params={
            "inputMint": signal.input_mint,
            "outputMint": signal.output_mint,
            "amount": signal.amount,
            "slippageBps": signal.slippage_bps,
            **({"taker": JUPITER_TAKER} if JUPITER_TAKER else {}),
        },
        headers=jupiter_headers(),
        timeout=TIMEOUT_SECONDS,
    )
    response_time = now_utc()
    monotonic_response_received = time.perf_counter()

    payload: dict[str, Any] = {}
    error_message = ""
    status = "ok"
    try:
        payload = response.json()
    except Exception:
        payload = {}
        error_message = response.text[:400]
    monotonic_payload_parsed = time.perf_counter()

    if response.status_code >= 400:
        status = "quote_error"
        if not error_message:
            error_message = json.dumps(payload)[:400]
    elif isinstance(payload, dict) and payload.get("error"):
        status = "quote_error"
        error_message = str(payload.get("error"))[:400]

    signal_ts_ms = epoch_ms(signal.signal_chain_time)
    detected_ts_ms = epoch_ms(signal.detected_local_time)
    quote_start_ts_ms = epoch_ms(request_started)
    quote_end_ts_ms = epoch_ms(response_time)
    detector_latency_ms = round((signal.detected_local_time - signal.signal_chain_time).total_seconds() * 1000, 3)
    quote_latency_ms = round((response_time - request_started).total_seconds() * 1000, 3)
    total_latency_ms = round((response_time - signal.signal_chain_time).total_seconds() * 1000, 3)
    quote_decode_ms = round((monotonic_payload_parsed - monotonic_response_received) * 1000, 3)
    quote_total_ms = round((monotonic_payload_parsed - monotonic_request_start) * 1000, 3)

    return {
        "signal_ts_ms": signal_ts_ms,
        "detected_ts_ms": detected_ts_ms,
        "quote_start_ts_ms": quote_start_ts_ms,
        "quote_end_ts_ms": quote_end_ts_ms,
        "detector_latency_ms": detector_latency_ms,
        "quote_latency_ms": quote_latency_ms,
        "total_latency_ms": total_latency_ms,
        "quote_ok": "true" if status == "ok" else "false",
        "error": error_message,
        "signal_id": signal.signal_id,
        "token_mint": signal.token_mint,
        "signal_chain_time": isoformat_z(signal.signal_chain_time),
        "detected_local_time": isoformat_z(signal.detected_local_time),
        "quote_request_time": isoformat_z(request_started),
        "quote_response_time": isoformat_z(response_time),
        "quote_decode_ms": quote_decode_ms,
        "quote_total_ms": quote_total_ms,
        "input_mint": signal.input_mint,
        "output_mint": signal.output_mint,
        "amount": str(signal.amount),
        "slippage_bps": str(signal.slippage_bps),
        "price_impact_pct": str(payload.get("priceImpactPct") or payload.get("priceImpact") or ""),
        "context_slot": str(payload.get("contextSlot") or signal.context_slot or ""),
        "status": status,
        "request_id": str(payload.get("requestId") or ""),
        "router": str(payload.get("router") or ""),
        "swap_type": str(payload.get("swapType") or ""),
        "volume_accel_10_300": str(signal.volume_accel_10_300 or ""),
    }


def error_latency_row(signal: SignalCandidate, error: str) -> dict[str, Any]:
    failure_time = now_utc()
    signal_ts_ms = epoch_ms(signal.signal_chain_time)
    detected_ts_ms = epoch_ms(signal.detected_local_time)
    failure_ts_ms = epoch_ms(failure_time)
    return {
        "signal_ts_ms": signal_ts_ms,
        "detected_ts_ms": detected_ts_ms,
        "quote_start_ts_ms": failure_ts_ms,
        "quote_end_ts_ms": failure_ts_ms,
        "detector_latency_ms": round((signal.detected_local_time - signal.signal_chain_time).total_seconds() * 1000, 3),
        "quote_latency_ms": 0.0,
        "total_latency_ms": round((failure_time - signal.signal_chain_time).total_seconds() * 1000, 3),
        "quote_ok": "false",
        "error": error[:400],
    }


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=REQUIRED_FIELDS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def metric_summary(values: list[float]) -> dict[str, float | int | None]:
    return {
        "count": len(values),
        "p50": percentile(values, 0.50),
        "p90": percentile(values, 0.90),
        "mean": round(sum(values) / len(values), 3) if values else None,
    }


def build_summary(rows: list[dict[str, Any]]) -> dict[str, Any]:
    success_rows = [row for row in rows if str(row.get("quote_ok")).strip().lower() == "true"]
    coverage = (len(success_rows) / len(rows) * 100.0) if rows else 0.0
    metrics = {
        "total_latency_ms": metric_summary(
            [value for value in (parse_float(row.get("total_latency_ms")) for row in rows) if value is not None]
        ),
        "quote_latency_ms": metric_summary(
            [value for value in (parse_float(row.get("quote_latency_ms")) for row in rows) if value is not None]
        ),
        "detector_latency_ms": metric_summary(
            [value for value in (parse_float(row.get("detector_latency_ms")) for row in rows) if value is not None]
        ),
    }
    p50_total = metrics["total_latency_ms"]["p50"]
    p90_total = metrics["total_latency_ms"]["p90"]
    observer_pass = bool(
        p50_total is not None
        and p90_total is not None
        and p50_total < 500
        and p90_total < 1000
        and coverage >= 90
    )
    return {
        "signals_processed": len(rows),
        "quote_successes": len(success_rows),
        "quote_coverage_pct": round(coverage, 3),
        "observer_pass": observer_pass,
        "gate": {
            "p50_total_latency_ms_lt": 500,
            "p90_total_latency_ms_lt": 1000,
            "quote_coverage_pct_gte": 90,
        },
        "metrics": metrics,
        "source_schema": REQUIRED_FIELDS,
    }


def write_summary(path: Path, summary: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(summary, ensure_ascii=True, indent=2), encoding="utf-8")


def print_summary(summary: dict[str, Any]) -> None:
    print("\nFast10 Observer summary")
    print(f"Signals processed: {summary['signals_processed']}")
    print(f"Quote successes: {summary['quote_successes']}")
    print(f"Quote coverage: {summary['quote_coverage_pct']:.2f}%")
    for metric in ["total_latency_ms", "quote_latency_ms", "detector_latency_ms"]:
        item = summary["metrics"][metric]
        if item["p50"] is not None:
            print(f"{metric}: p50={item['p50']:.3f} p90={item['p90']:.3f} mean={item['mean']:.3f}")
        else:
            print(f"{metric}: n/a")
    print("Observer PASS: yes" if summary["observer_pass"] else "Observer PASS: no")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Measure Fast10 signal -> Jupiter quote latency without signing or trading")
    parser.add_argument("--input", required=True, help="Path to CSV/JSONL detector output")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Path for observer_latency_live.csv")
    parser.add_argument("--summary-output", default="", help="Optional path for observer latency summary JSON")
    parser.add_argument("--threshold", default=str(FAST10_THRESHOLD), help="Fast10 threshold for volume_accel_10_300")
    parser.add_argument("--limit", type=int, default=0, help="Optional max number of signals to process")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    threshold = Decimal(str(args.threshold))
    input_path = Path(args.input)
    output_path = Path(args.output)
    summary_path = Path(args.summary_output) if args.summary_output else output_path.with_name(output_path.stem + "_summary.json")

    if not input_path.exists():
        print(f"Input not found: {input_path}", file=sys.stderr)
        return 1

    rows: list[dict[str, Any]] = []
    processed = 0

    for index, raw in enumerate(iter_rows(input_path), start=1):
        signal = normalize_signal(raw, index=index, threshold=threshold)
        if signal is None:
            continue
        try:
            row = request_quote(signal)
        except Exception as exc:
            row = error_latency_row(signal, str(exc))
        rows.append(row)
        processed += 1
        if args.limit and processed >= args.limit:
            break

    if not rows:
        print("No Fast10-compatible signals were processed.", file=sys.stderr)
        return 2

    write_csv(output_path, rows)
    summary = build_summary(rows)
    write_summary(summary_path, summary)
    print(f"Wrote observer CSV: {output_path}")
    print(f"Wrote observer summary: {summary_path}")
    print_summary(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
