[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FFC36B"
backgroundColor = "#030407"
secondaryBackgroundColor = "#0B0E14"
textColor = "#F5EFE2"
font = "sans serif"
